### ISSUE TITLE
Use a Value enum instead of multiple Options

### ISSUE THREAD

**Issue by HiruNya** [drbh/hotpot-db#2]
I've been playing around with this crate and I'm wondering why the `Query` struct uses multiple `Option`s for every type. Is there a reason for this?
e.g.
```rust
pub struct Query {
    // Unrelated
    pub string_value: Option<String>,
    pub bool_value: Option<bool>,
    pub float_value: Option<f32>,
    pub int_value: Option<i32>,
}
```
When `Hotpot::execute` is called, every `Option` is checked and if one of them is `Some(T)` then a query is executed. However the problem with this is that multiple `Option`s can be set and thus multiple different queries will be executed, the last query executed will be returned to the user. What value the user set last does not matter.

So I was thinking of using an enum instead.
e.g.
```rust
pub struct Query {
    // Unrelated
    pub value: Value,
}

pub enum Value {
    Boolean(bool),
    Float(f32),
    Integer(i32),
    String(String),
}
```

**Comment by drbh** [comment]
Hey @HiruNya Thanks for the interest and the feedback 🙂

**This is a great idea**, I agree that the `Options` should be replaced by an `Enum` and have implemented this pattern in the most recent update!

Here's a snippet of the updated structs:
https://github.com/drbh/hotpot-db/blob/c7913fb081effb540524ea3321097ca93a5f6fc4/src/lib.rs#L44-L68

The `execute` function uses `match` to resolve the correct type now, and presumably will avoid double executions.  

I would love to hear your feedback on this implementation and any other ideas you have for `hotpot-db`

**Comment by HiruNya** [comment]
It looks pretty good, I do have a few small nitpicks like using `unwrap_or_default` instead of `unwrap_or(Vec::new())` as the latter would allocated a new `Vec` whether or not the Result was Ok but that's not really an issue since the `Vec` would have 0 capacity anyway. I would suggest using the [clippy](https://github.com/rust-lang/rust-clippy) linter to pick up those small stuff.

Otherwise, it looks great! I'm going to close this issue now.
